import { fetchTmdb } from "@/lib/tmdb";

export const AI_MOVIE_GENRES = ["Drama", "Harakatli", "Triller", "Ilmiy fantastika", "Fantastik", "Jinoyat", "Komediya", "Romantik", "Tarix", "Multfilm", "Dahshat", "Musiqa"] as const;
export interface MovieFillInput { readonly title: string; readonly originalTitle: string; readonly year: number; readonly type: "MOVIE" | "SERIAL" }
export interface MovieFillOutput { readonly description: string; readonly shortDesc: string; readonly genres: string[]; readonly country: string; readonly language: string; readonly dubbing: string; readonly duration?: number; readonly imdbRating?: number; readonly posterUrl?: string; readonly backdropUrl?: string; readonly tmdbFound: boolean }

export async function fillMovieMetadata(input: MovieFillInput): Promise<MovieFillOutput> {
  const tmdb = await fetchTmdb(input.originalTitle, String(input.year), input.type);
  const ai = await askOpenRouter([`O'zbekcha nomi: ${input.title}.`, `Asl nomi: ${input.originalTitle}.`, `Yili: ${input.year}.`, tmdb.found ? `TMDB ma'lumoti:\nSyujet: ${tmdb.overview}\nJanrlar: ${(tmdb.genres ?? []).join(", ")}\nDavlat: ${tmdb.country}\nTil: ${tmdb.language}` : "TMDB'da topilmadi — ishonchsiz fakt to'qima.", "Faqat JSON qaytar:", `{\"description\":\"2-4 jumlali o'zbekcha tavsif\",\"shortDesc\":\"1 jumlali qisqa tavsif\",\"genres\":[\"faqat ruxsat etilgan janrlar\"],\"country\":\"o'zbekcha davlat\",\"language\":\"o'zbekcha til\"}`].join("\n"));
  if (!ai) throw new Error("AI_FILL_UNAVAILABLE");
  const genres = Array.isArray(ai["genres"]) ? (ai["genres"] as unknown[]).filter((value): value is string => typeof value === "string" && (AI_MOVIE_GENRES as readonly string[]).includes(value)) : [];
  return { description: text(ai["description"], 5000), shortDesc: text(ai["shortDesc"], 500), genres, country: text(ai["country"], 100) || tmdb.country || "", language: text(ai["language"], 100) || tmdb.language || "", dubbing: "O'zbek", ...(tmdb.runtime ? { duration: tmdb.runtime } : {}), ...(tmdb.rating ? { imdbRating: tmdb.rating } : {}), ...(tmdb.posterUrl ? { posterUrl: tmdb.posterUrl } : {}), ...(tmdb.backdropUrl ? { backdropUrl: tmdb.backdropUrl } : {}), tmdbFound: tmdb.found };
}
async function askOpenRouter(prompt: string): Promise<Record<string, unknown> | null> { const key = process.env.OPENROUTER_API_KEY; if (!key) return null; const response = await fetch("https://openrouter.ai/api/v1/chat/completions", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}`, "HTTP-Referer": "https://uzdub.com", "X-Title": "UZDUB Play" }, body: JSON.stringify({ model: process.env.OPENROUTER_MODEL || "openai/gpt-4o-mini", messages: [{ role: "system", content: "Sen kino ma'lumotlari eksperti va professional o'zbek tarjimonisan. Faqat to'g'ri JSON qaytar." }, { role: "user", content: prompt }], response_format: { type: "json_object" }, max_tokens: 900, temperature: 0.3 }) }); if (!response.ok) return null; const body = await response.json() as { choices?: { message?: { content?: string } }[] }; const content = body.choices?.[0]?.message?.content; if (!content) return null; try { return JSON.parse(content) as Record<string, unknown>; } catch { return null; } }
function text(value: unknown, max: number): string { return typeof value === "string" ? value.trim().slice(0, max) : ""; }
