import type { Movie } from "@/types/movie";

export const DEMO_MOVIES: Movie[] = [
  {
    id: "1",
    slug: "interstellar",
    title: "Yulduzlararo",
    originalTitle: "Interstellar",
    description: "Insoniyat mavjudligini ta'minlash uchun kosmik kemada sayohat qiluvchi olimlar va tadqiqotchilar guruhi haqida film. Ular Yerdan uzoqda yangi uy izlaydilar.",
    shortDesc: "Insoniyatning yashashi uchun kosmik sayohat. Vaqt va fazoning chegaralaridan oshib o'tgan odam.",
    posterUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2014, duration: 169,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.7, viewCount: 85600, isFeatured: true, isTrending: true,
    genres: [{ id: "1", name: "Ilmiy fantastika", slug: "ilmiy-fantastika" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "2",
    slug: "oppenheimer",
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    description: "Atom bombasini yaratgan olim J. Robert Oppenheimer hayoti haqida epik biografik drama.",
    shortDesc: "Atom bombasini yaratgan odam. Tarix oqimini o'zgartirgan kashfiyot.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2023, duration: 181,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.3, viewCount: 62300, isFeatured: true, isTrending: true,
    genres: [{ id: "3", name: "Tarix", slug: "tarix" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "3",
    slug: "dune-2",
    title: "Duna: 2-qism",
    originalTitle: "Dune: Part Two",
    description: "Paul Atreides va Fremenlar Harkonnenlar va Imperatorga qarshi kurash olib boradi.",
    shortDesc: "Cho'l sayyorasida imperiyalar to'qnashuvi. Bashorat va qismat haqida epos.",
    posterUrl: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2024, duration: 166,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.5, viewCount: 93100, isFeatured: true, isTrending: true,
    genres: [{ id: "1", name: "Ilmiy fantastika", slug: "ilmiy-fantastika" }, { id: "5", name: "Harakatli", slug: "harakatli" }],
  },
  {
    id: "4",
    slug: "parasite",
    title: "Parazit",
    originalTitle: "Parasite",
    description: "Kambag'al oila boy oilaning hayotiga asta-sekin kirib boradi. Oskar mukofotining eng yaxshi film sohibi.",
    shortDesc: "Kambag'al oila va boy oila o'rtasidagi keskin munosabatlar.",
    posterUrl: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2019, duration: 132,
    country: "Koreya", language: "Koreys", dubbing: "O'zbek",
    imdbRating: 8.5, viewCount: 47800, isTrending: true,
    genres: [{ id: "4", name: "Triller", slug: "triller" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "5",
    slug: "breaking-bad",
    title: "Yomon yo'l",
    originalTitle: "Breaking Bad",
    description: "Kimyo o'qituvchisi Walter White kasalligini bilgandan so'ng narkotik ishlab chiqaruvchiga aylanadi.",
    shortDesc: "Oddiy o'qituvchidan giyohvand moddalar imperiyasining rahbariga aylangan odam.",
    posterUrl: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2008,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 9.5, viewCount: 112400, isFeatured: true, isTrending: true,
    genres: [{ id: "4", name: "Triller", slug: "triller" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "6",
    slug: "inception",
    title: "Tush ichida tush",
    originalTitle: "Inception",
    description: "Dom Cobb inson ongiga kirib, sirlarni o'g'irlash bo'yicha tengsiz usta. U tushlar dunyosida ishlaydi.",
    shortDesc: "Tushlar dunyosida sirlar o'g'irlanadi. Haqiqat va xayol chegarasi yo'qoladi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/s2bT29y0ngXxxu2IA8AOzzXTRhd.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2010, duration: 148,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.8, viewCount: 78900, isFeatured: true, isTrending: true,
    genres: [{ id: "1", name: "Ilmiy fantastika", slug: "ilmiy-fantastika" }, { id: "4", name: "Triller", slug: "triller" }],
  },
  {
    id: "7",
    slug: "the-dark-knight",
    title: "Qorong'u Ritsar",
    originalTitle: "The Dark Knight",
    description: "Batman Gothemda tartibsizlik uyg'otayotgan Joker bilan kurashadi. Barcha zamonlarning eng yaxshi qahramonlik filmi.",
    shortDesc: "Batman va Jokerning ultimatum jangi. Yaxshilik va yomonlik o'rtasidagi chegara.",
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2008, duration: 152,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 9.0, viewCount: 134500, isFeatured: true, isTrending: true,
    genres: [{ id: "5", name: "Harakatli", slug: "harakatli" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "8",
    slug: "squid-game",
    title: "Kalamar O'yini",
    originalTitle: "Squid Game",
    description: "456 ta qarzga botgan odamlar katta mukofot uchun o'lik o'yinlarda ishtirok etadi.",
    shortDesc: "Hayot va o'lim o'yinida 456 ta ishtirokchi. Pul va yashash o'rtasidagi tanlov.",
    posterUrl: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/qw3J9cNeLioOLoR68WX7z79aCdK.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2021,
    country: "Koreya", language: "Koreys", dubbing: "O'zbek",
    imdbRating: 8.0, viewCount: 205600, isFeatured: true, isTrending: true,
    genres: [{ id: "4", name: "Triller", slug: "triller" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "9",
    slug: "the-godfather",
    title: "Krестный Otа",
    originalTitle: "The Godfather",
    description: "Korleone oilasi boshlig'i Don Vito Korleone va uning o'g'illari Nyu-Yorkdagi mafiya dunyosida kuch uchun kurashadi.",
    shortDesc: "Italyan mafiyasining eng buyuk eposi. Oila, kuch va sadoqat haqida.",
    posterUrl: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLe1rhdFwVlz.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/tmU7GeKVcMddjHMpAkCkMpzRDOY.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 1972, duration: 175,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 9.2, viewCount: 89300, isFeatured: true,
    genres: [{ id: "6", name: "Jinoyat", slug: "jinoyat" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "10",
    slug: "avengers-endgame",
    title: "Qasos oluvchilar: Yakuniy o'yin",
    originalTitle: "Avengers: Endgame",
    description: "Thanos barcha jonzotlarning yarmini yo'q qilgandan so'ng, qolgan Avengers-lar vaziyatni tiklash uchun so'nggi hamla uyushtiradilar.",
    shortDesc: "Marvel koinotining epik yakuniy jangi. Barcha qahramonlar birlashdi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2019, duration: 181,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.4, viewCount: 187600, isTrending: true,
    genres: [{ id: "5", name: "Harakatli", slug: "harakatli" }, { id: "7", name: "Fantastik", slug: "fantastik" }],
  },
  {
    id: "11",
    slug: "the-shawshank-redemption",
    title: "Shoushenk qochqinligi",
    originalTitle: "The Shawshank Redemption",
    description: "Nohaq qamalgan bank menejeri Andy Dufresne qamoqxona hayotini o'zgartiradi va ozodlikka yo'l izlaydi.",
    shortDesc: "Umid hech qachon o'lmaydi. Qamoqxona devorlaridan ortida erkinlik.",
    posterUrl: "https://image.tmdb.org/t/p/w500/lyQBXAljaleVBDhcDEzMaVlmNGI.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 1994, duration: 142,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 9.3, viewCount: 156800,
    genres: [{ id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "12",
    slug: "forrest-gump",
    title: "Forrest Gamp",
    originalTitle: "Forrest Gump",
    description: "Oddiy IQ ga ega Forrest Gamp hayotining turli bosqichlarida tarixiy voqealarga guvoh bo'ladi va yaqinlarini sevib qoladi.",
    shortDesc: "Hayot — shokolad qutisiga o'xshaydi. Sodda Forrest dunyoni hayron qoldiradi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 1994, duration: 142,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.8, viewCount: 98400,
    genres: [{ id: "2", name: "Drama", slug: "drama" }, { id: "8", name: "Romantik", slug: "romantik" }],
  },
  {
    id: "13",
    slug: "fight-club",
    title: "Mushtlashish to'garagi",
    originalTitle: "Fight Club",
    description: "Uyqusizlikdan aziyat chekayotgan ofis xodimi sirli sovun sotuvchisi Tayler Derden bilan uchrashadi va yashirin mushtlashish klubi tuzadi.",
    shortDesc: "Birinchi qoidasi: hech kim gapirmaydi. Ikkinchi qoidasi ham shunday.",
    posterUrl: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 1999, duration: 139,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.8, viewCount: 72300, isTrending: true,
    genres: [{ id: "4", name: "Triller", slug: "triller" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "14",
    slug: "pulp-fiction",
    title: "Arxiv fantastikasi",
    originalTitle: "Pulp Fiction",
    description: "Los-Anjelesda bir-biri bilan bog'liq uch hikoya: ikki killerk, bokschi va gangster xotini.",
    shortDesc: "Tarantinoning magistral asari. Jinoyat, yumor va noodatiy voqealar.",
    posterUrl: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 1994, duration: 154,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.9, viewCount: 63400,
    genres: [{ id: "6", name: "Jinoyat", slug: "jinoyat" }, { id: "4", name: "Triller", slug: "triller" }],
  },
  {
    id: "15",
    slug: "the-matrix",
    title: "Matritsa",
    originalTitle: "The Matrix",
    description: "Xaker Neo haqiqat deb bilgan dunyosining simulyatsiya ekanini bilib oladi va mashinalar zulmi ostidagi insoniyatni ozod qilish uchun kurashadi.",
    shortDesc: "Qizil yoki ko'k dori? Haqiqat yo xayol — tanlov senda.",
    posterUrl: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 1999, duration: 136,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.7, viewCount: 115600, isTrending: true,
    genres: [{ id: "1", name: "Ilmiy fantastika", slug: "ilmiy-fantastika" }, { id: "5", name: "Harakatli", slug: "harakatli" }],
  },
  {
    id: "16",
    slug: "goodfellas",
    title: "Yaxshi yigitlar",
    originalTitle: "GoodFellas",
    description: "Nyu-Yorkdagi italyan-amerikalik mafiyada yigirma besh yil o'tkazgan Henry Hillning hayoti.",
    shortDesc: "Mafiyaning ichki hayoti. Martin Skorseze'ning kinoasari.",
    posterUrl: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/sw7mordbZxgITU877yTpZCud90M.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 1990, duration: 146,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.7, viewCount: 54700,
    genres: [{ id: "6", name: "Jinoyat", slug: "jinoyat" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "17",
    slug: "schindlers-list",
    title: "Shindler ro'yxati",
    originalTitle: "Schindler's List",
    description: "Ikkinchi jahon urushi davrida nemis biznesmen Oskar Shindler minglab yahudiy ishchilarini natsistlar qo'lidan saqlab qoladi.",
    shortDesc: "Urush dahshatida insoniylikning buyuk namunasi. Haqiqiy voqea asosida.",
    posterUrl: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 1993, duration: 195,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 9.0, viewCount: 41200,
    genres: [{ id: "3", name: "Tarix", slug: "tarix" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "18",
    slug: "gladiator",
    title: "Gladiator",
    originalTitle: "Gladiator",
    description: "Rim generali Maximus imperatorni o'ldirishni buyurgan yovuz shahzoda Kommodudan o'ch olish uchun gladiator sifatida kurashadi.",
    shortDesc: "Rim arenasida o'ch va sharaf. Kuch va iroda haqidagi epos.",
    posterUrl: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/6WBIzCgmDCYrqh64yDREGeDk9d3.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2000, duration: 155,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.5, viewCount: 87600, isTrending: true,
    genres: [{ id: "5", name: "Harakatli", slug: "harakatli" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "19",
    slug: "the-lion-king",
    title: "Sher Qirol",
    originalTitle: "The Lion King",
    description: "Yosh sher Simba otasining o'limiga o'zi sababchi deb o'ylab, qochib ketadi. Yillar o'tib, u o'z taxtini qaytarishi kerak.",
    shortDesc: "Afrika savanasida qirollik va sadoqat haqida klassik animatsiya.",
    posterUrl: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/wXsQvli6tWqja51pYxXNG1LFIGV.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 1994, duration: 88,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.5, viewCount: 124300,
    genres: [{ id: "9", name: "Multfilm", slug: "multfilm" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "20",
    slug: "spirited-away",
    title: "Ruhlar shahriga sayohat",
    originalTitle: "Spirited Away",
    description: "10 yoshli Chihiro ruhlar va iblislar dunyosiga kirib qoladi. Ota-onasini qutqarish uchun u bu sirli dunyoda ishlashga majbur.",
    shortDesc: "Miyazakining shoh asari. Bolakay qahramonning ruhlar olamidagi sarguzashti.",
    posterUrl: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/bSXfU4dwZyBA1vMmXvejdRXBvuF.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2001, duration: 125,
    country: "Yaponiya", language: "Yapon", dubbing: "O'zbek",
    imdbRating: 8.6, viewCount: 67800,
    genres: [{ id: "9", name: "Multfilm", slug: "multfilm" }, { id: "7", name: "Fantastik", slug: "fantastik" }],
  },
  {
    id: "21",
    slug: "joker",
    title: "Joker",
    originalTitle: "Joker",
    description: "Arthur Fleck — kam baxtli komediyachi. Jamiyat tomonidan rad etilgach, u dunyoning eng mashhur yovuziga aylanadi.",
    shortDesc: "Yovuzlikning tug'ilishi. Jokerning og'riqli va real kelib chiqishi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1ZIz5LLWD1.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2019, duration: 122,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.4, viewCount: 143900, isFeatured: true, isTrending: true,
    genres: [{ id: "4", name: "Triller", slug: "triller" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "22",
    slug: "game-of-thrones",
    title: "Taxtlar o'yini",
    originalTitle: "Game of Thrones",
    description: "Yetti qirollik taxtini egallash uchun kuchli oilalar o'rtasida dahshatli urush boshlanadi. Dragonlar qaytadi.",
    shortDesc: "Taxt uchun urush. Dragonlar, siyosat va xiyonat — barchasi bitta serialda.",
    posterUrl: "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2011,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 9.2, viewCount: 298400, isFeatured: true, isTrending: true,
    genres: [{ id: "7", name: "Fantastik", slug: "fantastik" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "23",
    slug: "stranger-things",
    title: "Begona narsalar",
    originalTitle: "Stranger Things",
    description: "Indiana shtatidagi kichik shaharchada yigit g'oyib bo'lgach, uning do'stlari, onasi va politsiyachi g'ayritabiiy sirlarni aniqlaydi.",
    shortDesc: "80-yillar nostalji va dahshat. Upside Down dunyosidagi do'stlik haqida.",
    posterUrl: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2016,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.7, viewCount: 178900, isFeatured: true, isTrending: true,
    genres: [{ id: "10", name: "Dahshat", slug: "dahshat" }, { id: "7", name: "Fantastik", slug: "fantastik" }],
  },
  {
    id: "24",
    slug: "the-witcher",
    title: "Sehr ustasi",
    originalTitle: "The Witcher",
    description: "Monster ovchisi Geralt, Triss va kelajakning qudratli malikasi Ciri o'rtasidagi taqdir haqida fantastik avantyura.",
    shortDesc: "Sehr va monsters dunyosi. Geralt — yolg'iz ovchi va qo'rqmas jangchi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2019,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.2, viewCount: 134500, isTrending: true,
    genres: [{ id: "7", name: "Fantastik", slug: "fantastik" }, { id: "5", name: "Harakatli", slug: "harakatli" }],
  },
  {
    id: "25",
    slug: "money-heist",
    title: "Pul o'g'irlanadi",
    originalTitle: "Money Heist",
    description: "Muhandis laqabli asrorli odam va uning guruhi Ispaniya milliy bankini bosib olishi uchun murakkab plan tuzadi.",
    shortDesc: "Ispaniyaning eng katta banki qamal qilindi. Qizil kostyumlar, Salvador Dali niqlari.",
    posterUrl: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/x9HHGmGCv2RJaqzMFdxqoGHMbJF.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2017,
    country: "Ispaniya", language: "Ispan", dubbing: "O'zbek",
    imdbRating: 8.3, viewCount: 224600, isFeatured: true, isTrending: true,
    genres: [{ id: "4", name: "Triller", slug: "triller" }, { id: "6", name: "Jinoyat", slug: "jinoyat" }],
  },
  {
    id: "26",
    slug: "peaky-blinders",
    title: "Keskin ko'rinishlilar",
    originalTitle: "Peaky Blinders",
    description: "Birinchi jahon urushidan so'ng Birmingem shahrida Shelbey oilasi o'z jinoiy imperiyasini kengaytiradi.",
    shortDesc: "Birmingem ko'chalarida jinoiy imperiya quruvchi Shelbey oilasi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVn3nyfVn2.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/wiE9doxiLwq3WgJDGXr5WkZl7SR.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2013,
    country: "Britaniya", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.8, viewCount: 98700, isTrending: true,
    genres: [{ id: "6", name: "Jinoyat", slug: "jinoyat" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "27",
    slug: "dark",
    title: "Qorong'ulik",
    originalTitle: "Dark",
    description: "Nemis shaharchasida bolaning g'oyib bo'lishi to'rt oilani vaqt sayohati va murakkab sir bilan bog'liq voqealarga olib keladi.",
    shortDesc: "Vaqt halqasi va oilaviy sirlar. Nemis seriallarining eng yaxshisi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/apbrbWs5M9hvPMCeLEBJe6EMRE4.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/j3gS6qCBedRFJWbxPBCsD4z1M0O.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2017,
    country: "Germaniya", language: "Nemis", dubbing: "O'zbek",
    imdbRating: 8.8, viewCount: 87300,
    genres: [{ id: "4", name: "Triller", slug: "triller" }, { id: "1", name: "Ilmiy fantastika", slug: "ilmiy-fantastika" }],
  },
  {
    id: "28",
    slug: "wednesday",
    title: "Chorshanba",
    originalTitle: "Wednesday",
    description: "Addams oilasining qorong'u qizi Chorshanba Nevermore akademiyasida o'qiy boshlaydi va dahshatli sirlarni yechadi.",
    shortDesc: "Addams oilasining g'alati qizi. Akademiya sirları va dahshat.",
    posterUrl: "https://image.tmdb.org/t/p/w500/jeGtaMwGxPmQN5xM4ClnwPQcDef.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2022,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.1, viewCount: 198700, isTrending: true,
    genres: [{ id: "10", name: "Dahshat", slug: "dahshat" }, { id: "11", name: "Komediya", slug: "komediya" }],
  },
  {
    id: "29",
    slug: "the-mandalorian",
    title: "Mandalorian",
    originalTitle: "The Mandalorian",
    description: "Yulduzlar urushi koinotida yolg'iz mandalorian sayyohgir va sirli kichik mavjudot Grogu haqida sarguzasht.",
    shortDesc: "Yulduzlar urushi olamida yangi qahramon. Bu yo'l — bu yo'l.",
    posterUrl: "https://image.tmdb.org/t/p/w500/sWgBv7LV2renceCiai3KFUYJdk.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/o7qi2v4uWQ8bZ1tW3KI0Ztn2epk.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2019,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.7, viewCount: 165400, isTrending: true,
    genres: [{ id: "1", name: "Ilmiy fantastika", slug: "ilmiy-fantastika" }, { id: "5", name: "Harakatli", slug: "harakatli" }],
  },
  {
    id: "30",
    slug: "avatar",
    title: "Avatar",
    originalTitle: "Avatar",
    description: "Pandora sayyorasida dengizchi Jake Sully na'vi xalqi bilan birga korporatsiya va harbiy kuchlarga qarshi kurashadi.",
    shortDesc: "Pandora — hayot manbai. Tabiat va texnologiya o'rtasidagi to'qnashuv.",
    posterUrl: "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/o0s4XsEDfDlvit5pDRKjzXR4pp2.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2009, duration: 162,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 7.9, viewCount: 213400, isTrending: true,
    genres: [{ id: "1", name: "Ilmiy fantastika", slug: "ilmiy-fantastika" }, { id: "5", name: "Harakatli", slug: "harakatli" }],
  },
  {
    id: "31",
    slug: "spider-man-no-way-home",
    title: "O'rgimchak-odam: Uyga yo'l yo'q",
    originalTitle: "Spider-Man: No Way Home",
    description: "Peter Parker parallel koinotlardan kelgan yovuzlar bilan kurashadi va o'z hayotini qurbon qilishga tayyor bo'ladi.",
    shortDesc: "Ko'p koinot. Ko'p Spider-Man. Hamma narsa xavf ostida.",
    posterUrl: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2021, duration: 148,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.3, viewCount: 156700, isTrending: true,
    genres: [{ id: "5", name: "Harakatli", slug: "harakatli" }, { id: "7", name: "Fantastik", slug: "fantastik" }],
  },
  {
    id: "32",
    slug: "top-gun-maverick",
    title: "Top Gun: Maverick",
    originalTitle: "Top Gun: Maverick",
    description: "Maverick 30 yildan so'ng Top Gun akademiyasiga qaytadi va eski raqibi o'g'lini o'qitishga majbur bo'ladi.",
    shortDesc: "Osmonning haqiqiy hukmdori qaytdi. Tezlik, jasorat va qurbonlik.",
    posterUrl: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2022, duration: 130,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.3, viewCount: 143200, isTrending: true,
    genres: [{ id: "5", name: "Harakatli", slug: "harakatli" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "33",
    slug: "john-wick",
    title: "Jon Uik",
    originalTitle: "John Wick",
    description: "Itini o'ldirgan va mashinasini o'g'irlagan mafia o'g'illaridan o'ch olish uchun nafaqadagi killerk Jon Uik qaytadi.",
    shortDesc: "It uchun o'ch. Eng xavfli killerk uyg'ondi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/fZPSd91pGjdpjBnClReA6hONEFB.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/umC04Cozevu8nn3JTDJ1pc7PVTn.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2014, duration: 101,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 7.4, viewCount: 98300, isTrending: true,
    genres: [{ id: "5", name: "Harakatli", slug: "harakatli" }, { id: "4", name: "Triller", slug: "triller" }],
  },
  {
    id: "34",
    slug: "the-boys",
    title: "Yigitlar",
    originalTitle: "The Boys",
    description: "Superflar yovuz va korporativ bo'lib qolganda, Butcher boshchiligidagi oddiy odamlar guruhi ularga qarshi kurashadi.",
    shortDesc: "Superqahramonlar aslida yovuz bo'lsa-chi? To'liq real javob.",
    posterUrl: "https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2019,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.7, viewCount: 187600, isTrending: true,
    genres: [{ id: "5", name: "Harakatli", slug: "harakatli" }, { id: "4", name: "Triller", slug: "triller" }],
  },
  {
    id: "35",
    slug: "ozark",
    title: "Ozark",
    originalTitle: "Ozark",
    description: "Moliyachilar Martinning oilasi Meksika karteli puli yuvish biznesiga aralashib qoladi va Ozark ko'liga ko'chib o'tishga majbur bo'ladi.",
    shortDesc: "Oddiy oila — xavfli biznes. Pul yuviladi, hayot qilinadi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/pCGyPEp0vBb5TVpSrHEIhAzpxUg.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/5f1X9JVDUFU4MXOX7E3LBuDJoFa.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2017,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.4, viewCount: 76800,
    genres: [{ id: "4", name: "Triller", slug: "triller" }, { id: "6", name: "Jinoyat", slug: "jinoyat" }],
  },
  {
    id: "36",
    slug: "mindhunter",
    title: "Ong ovchisi",
    originalTitle: "Mindhunter",
    description: "FBI agentlari serial qotillar psixologiyasini o'rganish va yangi jinoyatlarni oldini olish uchun mahbuslarni so'roq qiladi.",
    shortDesc: "Serial qotillar miyasiga sayohat. FBI ning qorong'u tadqiqoti.",
    posterUrl: "https://image.tmdb.org/t/p/w500/tegBpjPZSFQMDTlBrMpMWkUzMk3.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/a3UVoNVqVMHRy8KVO3mFqBYXymg.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2017,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.6, viewCount: 54300,
    genres: [{ id: "6", name: "Jinoyat", slug: "jinoyat" }, { id: "4", name: "Triller", slug: "triller" }],
  },
  {
    id: "37",
    slug: "1917",
    title: "1917",
    originalTitle: "1917",
    description: "Birinchi jahon urushida ikki askar dushman liniyasidan o'tib, minglarcha hayot qutqaradigan xabarni yetkazishi kerak. Bir suratga olingan.",
    shortDesc: "Bir missiya, bir nafas. Urush dahshatining real portlashi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/tJDo0ZTMHHjBMCaMzAg6bLPMxCL.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2019, duration: 119,
    country: "Britaniya", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.3, viewCount: 62400,
    genres: [{ id: "3", name: "Tarix", slug: "tarix" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "38",
    slug: "whiplash",
    title: "Lash",
    originalTitle: "Whiplash",
    description: "Harbiy akademiya baraban chaluvchisi talaba Fletcher degan shafqatsiz o'qituvchi bilan to'qnashadi. Mukammallikka erishish narxi nima?",
    shortDesc: "Mukammallik uchun qanday narx to'laysiz? Shafqatsiz ustoz va iqtidorli shogird.",
    posterUrl: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2014, duration: 107,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.5, viewCount: 43600,
    genres: [{ id: "2", name: "Drama", slug: "drama" }, { id: "12", name: "Musiqa", slug: "musiqa" }],
  },
  {
    id: "39",
    slug: "the-revenant",
    title: "Tirilganlar",
    originalTitle: "The Revenant",
    description: "1820-yillarda ovchi Hugh Glass ayiq hujumidan so'ng o'lganga qo'yib ketiladi. U o'lim va sovuqdan omon qolib, do'stini topishga qasamyod qiladi.",
    shortDesc: "Tabiatning eng qattiq sinovida omon qolgan odam. O'ch va yashash irodasi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/ji3ecJphATlVgWNY0B0RVXZizdf.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/pIUvQ9Ed35wlWhY2oU6OmwEsmzG.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2015, duration: 156,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.0, viewCount: 57800,
    genres: [{ id: "2", name: "Drama", slug: "drama" }, { id: "5", name: "Harakatli", slug: "harakatli" }],
  },
  {
    id: "40",
    slug: "the-grand-budapest-hotel",
    title: "Buyuk Budapesht mehmonxonasi",
    originalTitle: "The Grand Budapest Hotel",
    description: "Evcildagi mehmonxona direktori Gustave va uning bellboyi Zero Mostel o'g'irlik va qotillik ishi bilan aralashib qoladi.",
    shortDesc: "Wes Andersonning quvnoq kino olamida retro avantyura.",
    posterUrl: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2014, duration: 99,
    country: "Germaniya", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.1, viewCount: 38900,
    genres: [{ id: "11", name: "Komediya", slug: "komediya" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "41",
    slug: "mad-max-fury-road",
    title: "Aqldan ozgan Maks: G'azab yo'li",
    originalTitle: "Mad Max: Fury Road",
    description: "Apokaliptik cho'lda Maks va Furiosa Immortan Jo va uning lashkarlari ketidan qochadi. Non-stop harakatli film.",
    shortDesc: "To'xtamasiz quvish. Apokaliptik dunyoda erkinlik uchun kurash.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/phszHPFMBMkCvtaAYpHGewrEDR9.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2015, duration: 120,
    country: "Avstraliya", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.1, viewCount: 76500,
    genres: [{ id: "5", name: "Harakatli", slug: "harakatli" }, { id: "1", name: "Ilmiy fantastika", slug: "ilmiy-fantastika" }],
  },
  {
    id: "42",
    slug: "get-out",
    title: "Qoch",
    originalTitle: "Get Out",
    description: "Qora tanli Kris qiz do'stining oq tanli oilasiga tashrif buyuradi. Lekin bu oila dahshatli sirga ega.",
    shortDesc: "Irqchilik va dahshat. Jordan Peele'ning debüt masterpiece.",
    posterUrl: "https://image.tmdb.org/t/p/w500/tFXcEccSUMyeFeIM7oTCm8Z3LCu.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/bu2hJFkXGIVbCpwpkPfMQEcZOPvEJe4t22MjXEBCUQs.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2017, duration: 104,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 7.7, viewCount: 48200,
    genres: [{ id: "10", name: "Dahshat", slug: "dahshat" }, { id: "4", name: "Triller", slug: "triller" }],
  },
  {
    id: "43",
    slug: "hereditary",
    title: "Meros",
    originalTitle: "Hereditary",
    description: "Oilaviy fojiadan so'ng Annie Graham va uning oilasi dahshatli sirni bilib oladi — oiladagi irsiy la'nat.",
    shortDesc: "Oilaviy meros dahshat. Zamonaviy dahshat kinoning eng dahshatlisi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/V9T0BkSBBD0E2FPxnYN5U5pIa8a.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/r5XbCz7v3G5g8PJCVMJxnEhLnp5.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2018, duration: 127,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 7.3, viewCount: 32400,
    genres: [{ id: "10", name: "Dahshat", slug: "dahshat" }, { id: "4", name: "Triller", slug: "triller" }],
  },
  {
    id: "44",
    slug: "knives-out",
    title: "Pichoqlar tashqarida",
    originalTitle: "Knives Out",
    description: "Mashhur detektiv romanchining o'limi tergov qilinmoqda. Barcha oila a'zolari shubhali.",
    shortDesc: "Kim o'ldirdi? Detektiv Benuaga topshiriq berildi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/pThyQovXQrws2Q07ZtL8f2ivMsB.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/3BDFODHBMBbFrwGAL1l4TpuqsTh.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2019, duration: 130,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 7.9, viewCount: 54300,
    genres: [{ id: "6", name: "Jinoyat", slug: "jinoyat" }, { id: "11", name: "Komediya", slug: "komediya" }],
  },
  {
    id: "45",
    slug: "the-irishman",
    title: "Irlandiyalik",
    originalTitle: "The Irishman",
    description: "Kamion haydovchisi Frank Sheeran mafiyaga qo'shiladi va Teamsters kasaba uyushmasida yuqori lavozimga erishadi.",
    shortDesc: "Skorseze'ning epik jinoiy dramasi. 60 yillik mafiya hayoti.",
    posterUrl: "https://image.tmdb.org/t/p/w500/mbm8k3GFhXS0Rock5MZIpOHlBnC.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/eB6WVFoGdlz7yFCyeUvFxnkVxmk.jpg",
    type: "MOVIE", status: "PUBLISHED", year: 2019, duration: 209,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 7.8, viewCount: 38700,
    genres: [{ id: "6", name: "Jinoyat", slug: "jinoyat" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "46",
    slug: "succession",
    title: "Vorislik",
    originalTitle: "Succession",
    description: "Media magnati Logan Roy nafaqaga chiqmoqchi. Uning to'rt farzandi korporatsiya va ota qalbi uchun kurashadi.",
    shortDesc: "Boylik va kuch uchun oilaviy urush. HBO ning eng zo'r dramasi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/e2X8g1RAgHyOjNaDdKMJkH3dRfr.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/qnKOm3b7JE1URwVzjRFJdyUMPnA.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2018,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.9, viewCount: 112400, isTrending: true,
    genres: [{ id: "2", name: "Drama", slug: "drama" }, { id: "11", name: "Komediya", slug: "komediya" }],
  },
  {
    id: "47",
    slug: "chernobyl",
    title: "Chernobil",
    originalTitle: "Chernobyl",
    description: "1986-yilgi Chernobil yadroviy halokati va uni yashirishga uringan Sovet tizimiga qarshi kurash haqida.",
    shortDesc: "Tarix bo'lib ketgan fojia. Haqiqatning narxi nima?",
    posterUrl: "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2019,
    country: "AQSh/Britaniya", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 9.4, viewCount: 134800, isFeatured: true,
    genres: [{ id: "3", name: "Tarix", slug: "tarix" }, { id: "2", name: "Drama", slug: "drama" }],
  },
  {
    id: "48",
    slug: "true-detective",
    title: "Haqiqiy dedektiv",
    originalTitle: "True Detective",
    description: "Louisiana botqoqliklarida serial qotillik izi. Ikki detektiv o'n yillik sirni echishga harakat qiladi.",
    shortDesc: "Botqoqlik serial qotili. Ikki detektiv, o'n yillik afsun.",
    posterUrl: "https://image.tmdb.org/t/p/w500/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/ab6HXZhXOjBEDGP1o8oVV4Q3fvk.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2014,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 9.0, viewCount: 87400,
    genres: [{ id: "6", name: "Jinoyat", slug: "jinoyat" }, { id: "4", name: "Triller", slug: "triller" }],
  },
  {
    id: "49",
    slug: "severance",
    title: "Ajratish",
    originalTitle: "Severance",
    description: "Lumon Industries xodimlarining ish va shaxsiy xotiralari chirurgik yo'l bilan ajratilgan. Ular o'z hayotining sirini ochishga harakat qiladi.",
    shortDesc: "Ish va hayot abadiy ajratildi. Korporatsiya sirlari va o'zlik izlash.",
    posterUrl: "https://image.tmdb.org/t/p/w500/pqzjCxPVc9sADSBDkRmfBfGJLmN.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/cBfhd9VC7dRdlMqS9BfSJi9F2kw.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2022,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.7, viewCount: 98300, isTrending: true,
    genres: [{ id: "4", name: "Triller", slug: "triller" }, { id: "1", name: "Ilmiy fantastika", slug: "ilmiy-fantastika" }],
  },
  {
    id: "50",
    slug: "house-of-the-dragon",
    title: "Ajdaho uyi",
    originalTitle: "House of the Dragon",
    description: "Taxtlar o'yinidan 200 yil avval Targaryen oilasi o'z orasida dahshatli fuqarolar urushini boshlaydı.",
    shortDesc: "Targaryen sulolasining qulashi. Ajdaholar urushi boshlanadi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    type: "SERIAL", status: "PUBLISHED", year: 2022,
    country: "AQSh", language: "Ingliz", dubbing: "O'zbek",
    imdbRating: 8.4, viewCount: 176500, isFeatured: true, isTrending: true,
    genres: [{ id: "7", name: "Fantastik", slug: "fantastik" }, { id: "2", name: "Drama", slug: "drama" }],
  },
];

export const DEMO_FEATURED = DEMO_MOVIES.filter((m) => m.isFeatured);
export const DEMO_TRENDING = DEMO_MOVIES.filter((m) => m.isTrending);
export const DEMO_SERIALS = DEMO_MOVIES.filter((m) => m.type === "SERIAL");
export const DEMO_KINOLAR = DEMO_MOVIES.filter((m) => m.type === "MOVIE");
