"use client";

import Image from "next/image";
import Link from "next/link";
import { Layers3, Play, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { Episode } from "@/types/movie";

type Props = { slug: string; episodes: Episode[]; activeSeason?: number; activeEpisode?: number; title?: string; compact?: boolean; sidebar?: boolean; fallbackImage?: string };

export function normalizeEpisodes(episodes: Episode[]): Episode[] {
  return [...episodes].map((episode) => ({ ...episode, season: Number(episode.season) || 1, episode: Number(episode.episode) || 1 })).sort((a, b) => a.season - b.season || a.episode - b.episode);
}

function EpisodeThumbnail({ src }: { src?: string }) {
  const [failed, setFailed] = useState(false);
  return <div className="relative h-[66px] w-[104px] shrink-0 overflow-hidden rounded-lg bg-gradient-to-br from-violet-950 via-slate-950 to-black">{src && !failed ? <Image src={src} alt="" fill sizes="104px" className="object-cover object-center" onError={() => setFailed(true)} /> : null}<span className="absolute inset-0 bg-gradient-to-r from-black/20 via-transparent to-black/35" /><span className="absolute inset-0 flex items-center justify-center"><Play className="h-5 w-5 text-violet-200 drop-shadow-[0_1px_4px_rgba(0,0,0,.9)]" /></span></div>;
}

export default function SeasonEpisodeSelector({ slug, episodes, activeSeason, activeEpisode, title, compact = false, sidebar = false, fallbackImage }: Props) {
  const groups = useMemo(() => { const map = new Map<number, Episode[]>(); for (const episode of normalizeEpisodes(episodes)) map.set(episode.season, [...(map.get(episode.season) ?? []), episode]); return [...map.entries()].map(([season, items]) => ({ season, episodes: items })); }, [episodes]);
  const [selectedSeason, setSelectedSeason] = useState(activeSeason && groups.some((group) => group.season === activeSeason) ? activeSeason : groups[0]?.season);
  useEffect(() => { if (activeSeason && groups.some((group) => group.season === activeSeason)) setSelectedSeason(activeSeason); }, [activeSeason, groups]);
  if (!groups.length || !selectedSeason) return null;
  const current = groups.find((group) => group.season === selectedSeason) ?? groups[0];
  const seasons = <div className="mb-3 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{groups.map((group) => { const active = group.season === selectedSeason; return <button key={group.season} type="button" onClick={() => setSelectedSeason(group.season)} className="shrink-0 rounded-lg px-3 py-2 text-left text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-300" style={{ background: active ? "rgba(124,58,237,.38)" : "rgba(255,255,255,.04)", border: active ? "1px solid rgba(216,180,254,.8)" : "1px solid rgba(255,255,255,.1)", color: "white" }}><b>{group.season}-fasl</b>{!sidebar && <span className="ml-2 text-xs text-violet-200">{group.episodes.length} qism</span>}</button>; })}</div>;
  if (sidebar) return <section className="rounded-2xl p-3 md:p-4" style={{ background: "linear-gradient(145deg,rgba(22,18,34,.96),rgba(10,11,19,.98))", border: "1px solid rgba(167,139,250,.28)", boxShadow: "0 16px 42px rgba(0,0,0,.24)" }} aria-label="Fasllar va qismlar"><div className="mb-3 flex items-center justify-between gap-2"><h2 className="flex items-center gap-2 text-lg font-bold text-white"><Layers3 className="h-5 w-5 text-violet-300" />Fasllar va qismlar</h2><span className="text-xs text-violet-200">{current.episodes.length} qism</span></div>{seasons}<div className="max-h-[500px] space-y-2 overflow-y-auto pr-1 [scrollbar-color:rgba(167,139,250,.6)_transparent]">{current.episodes.map((episode) => { const selected = episode.season === activeSeason && episode.episode === activeEpisode; return <Link key={episode.id} href={`/serial/${slug}/qism/${episode.season}/${episode.episode}`} aria-current={selected ? "page" : undefined} className="flex min-h-[84px] gap-2.5 rounded-xl p-2 transition-all hover:bg-white/[.045] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-300" style={{ background: selected ? "linear-gradient(135deg,rgba(124,58,237,.34),rgba(46,16,101,.24))" : "rgba(255,255,255,.025)", border: selected ? "1px solid rgba(192,132,252,.92)" : "1px solid rgba(255,255,255,.09)", boxShadow: selected ? "0 0 18px rgba(139,92,246,.36)" : "none" }}><EpisodeThumbnail src={episode.previewUrl || fallbackImage} /><div className="min-w-0 flex-1 self-center"><p className="flex items-center gap-1.5 text-sm font-semibold text-white">{selected && <Play className="h-3.5 w-3.5 shrink-0 fill-violet-300 text-violet-300" />}{episode.episode}-qism</p>{episode.duration ? <p className="mt-1 text-xs" style={{ color: "var(--text-muted)" }}>{episode.duration} daqiqa</p> : null}</div></Link>; })}</div></section>;
  return <section className={compact ? "mt-5" : "mx-auto max-w-[1120px] px-4 py-8 md:px-8"} aria-label="Fasllar va qismlar"><div className="overflow-hidden rounded-2xl p-4 md:rounded-3xl md:p-5" style={{ background: "linear-gradient(145deg,rgba(22,18,34,.92),rgba(10,11,19,.94))", border: "1px solid rgba(167,139,250,.26)", boxShadow: "inset 0 1px 0 rgba(255,255,255,.06),0 16px 42px rgba(0,0,0,.22)" }}><div className="mb-4 flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-lg font-bold text-white md:text-xl"><span className="flex h-9 w-9 items-center justify-center rounded-xl" style={{ color: "#d8b4fe", background: "rgba(124,58,237,.16)", border: "1px solid rgba(167,139,250,.3)" }}><Layers3 className="h-4 w-4" /></span>Fasllar va qismlar</h2><span className="hidden items-center gap-1.5 text-xs font-medium text-violet-300 sm:flex"><Sparkles className="h-3.5 w-3.5" />Qismni tanlang</span></div>{seasons}<div className="grid grid-cols-2 gap-2.5 border-t pt-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6" style={{ borderColor: "rgba(255,255,255,.07)" }}>{current.episodes.map((episode) => { const selected = episode.season === activeSeason && episode.episode === activeEpisode; return <Link key={episode.id} href={`/serial/${slug}/qism/${episode.season}/${episode.episode}`} className="relative min-w-0 rounded-xl p-3 transition-all hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400" style={{ background: selected ? "linear-gradient(135deg,rgba(124,58,237,.42),rgba(46,16,101,.34))" : "linear-gradient(135deg,rgba(255,255,255,.075),rgba(255,255,255,.025))", border: selected ? "1px solid rgba(192,132,252,.9)" : "1px solid rgba(255,255,255,.1)", boxShadow: selected ? "0 0 22px rgba(139,92,246,.36)" : "none" }}><p className="text-sm font-semibold text-white">{episode.episode}-qism</p>{episode.duration ? <p className="mt-1.5 text-xs" style={{ color: selected ? "#e9d5ff" : "var(--text-muted)" }}>{episode.duration} daqiqa</p> : null}</Link>; })}</div>{title && <p className="mt-4 text-center text-xs" style={{ color: "var(--text-muted)" }}>{title} — {selectedSeason}-fasl, {current.episodes.length} qism</p>}</div></section>;
}
