"use client";

import { useState } from "react";
import { LogOut, ShieldCheck, X } from "lucide-react";
import { signOut } from "next-auth/react";

export default function ProfileLogoutButton() {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const logout = async () => { setLoading(true); await signOut({ redirectTo: "/" }); };
  return <><section className="mt-8 rounded-2xl p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4" style={{ background: "linear-gradient(135deg,rgba(55,20,42,.24),rgba(16,16,27,.92))", border: "1px solid rgba(244,63,94,.25)" }}><div className="flex gap-3"><span className="h-10 w-10 rounded-xl flex items-center justify-center text-rose-300" style={{ background: "rgba(244,63,94,.12)" }}><ShieldCheck className="h-5 w-5" /></span><div><h2 className="font-semibold text-white">Hisob xavfsizligi</h2><p className="text-sm mt-1" style={{ color: "var(--text-muted)" }}>Joriy akkauntdan ushbu qurilmada chiqish.</p></div></div><button onClick={() => setOpen(true)} className="inline-flex justify-center items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold text-rose-200 transition hover:bg-rose-500/15" style={{ border: "1px solid rgba(244,63,94,.38)" }}><LogOut className="h-4 w-4" />Saytdan chiqish</button></section>{open && <div className="fixed inset-0 z-[100] flex items-end sm:items-center justify-center p-4" role="dialog" aria-modal="true"><button onClick={() => setOpen(false)} className="absolute inset-0 bg-black/70 backdrop-blur-sm" aria-label="Modalni yopish" /><section className="relative w-full max-w-sm rounded-2xl p-6" style={{ background: "linear-gradient(145deg,#181126,#0d0e19)", border: "1px solid rgba(168,85,247,.4)", boxShadow: "0 24px 70px rgba(0,0,0,.5)" }}><button onClick={() => setOpen(false)} className="absolute top-4 right-4 text-gray-400 hover:text-white"><X className="h-5 w-5" /></button><div className="h-11 w-11 rounded-xl flex items-center justify-center text-rose-300" style={{ background: "rgba(244,63,94,.13)" }}><LogOut className="h-5 w-5" /></div><h2 className="mt-4 text-xl font-bold text-white">Hisobdan chiqishni xohlaysizmi?</h2><p className="mt-2 text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>Siz ushbu qurilmadagi akkauntingizdan chiqasiz.</p><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={() => setOpen(false)} disabled={loading} className="rounded-xl py-2.5 text-sm text-white" style={{ border: "1px solid var(--border)" }}>Bekor qilish</button><button onClick={() => void logout()} disabled={loading} className="rounded-xl py-2.5 text-sm font-semibold text-white disabled:opacity-60" style={{ background: "linear-gradient(135deg,#be123c,#e11d48)" }}>{loading ? "Chiqilmoqda..." : "Chiqish"}</button></div></section></div>}</>;
}
