"use client";

import Link from "next/link";
import { CalendarDays, ChevronLeft, Globe2, Mic2, Sparkles, VideoOff } from "lucide-react";
import type { Movie } from "@/types/movie";
import UzdubPlayer from "@/components/player/UzdubPlayer";

export default function TomashaClient({ movie }: { movie: Movie }) {
  return <div className="min-h-screen flex flex-col" style={{ background: "#000" }}>
    <div className="flex items-center gap-3 px-4 py-3" style={{ background: "#0a0a0f", borderBottom: "1px solid var(--border)" }}><Link href={`/kino/${movie.slug}`} className="flex items-center gap-2 text-white hover:text-gray-300 transition-colors"><ChevronLeft className="h-5 w-5" /><span className="text-sm font-medium">{movie.title}</span></Link><span className="hidden sm:block text-xs" style={{ color: "var(--text-muted)" }}>Premium tomosha rejimi</span></div>
    <div className="w-full max-w-[1120px] mx-auto px-3 md:px-0 pt-5 md:pt-8"><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-violet-200"><span className="rounded-full px-2.5 py-1" style={{ background: "rgba(124,58,237,.2)", border: "1px solid rgba(196,132,252,.28)" }}>✦ PREMIUM PLAYER</span><span style={{ color: "var(--text-muted)" }}>HD sifatda tomosha qiling</span></div><div className="relative rounded-2xl md:rounded-3xl p-px" style={{ background: "linear-gradient(135deg, rgba(192,132,252,0.9), rgba(124,58,237,0.15) 42%, rgba(236,72,153,0.75))", boxShadow: "0 0 22px rgba(124,58,237,0.42), 0 0 65px rgba(139,92,246,0.18)" }}><div className="absolute -inset-4 -z-10 rounded-[2.2rem] opacity-70 blur-3xl" style={{ background: "radial-gradient(ellipse at 15% 15%, rgba(168,85,247,0.46), transparent 45%), radial-gradient(ellipse at 85% 90%, rgba(236,72,153,0.28), transparent 48%)" }} /><div className="overflow-hidden rounded-[15px] md:rounded-[23px] bg-black">{movie.videoUrl ? <UzdubPlayer src={movie.videoUrl} poster={movie.backdropUrl || movie.posterUrl} movieId={movie.id} /> : <div className="w-full flex flex-col items-center justify-center gap-3 text-center" style={{ aspectRatio: "16 / 9", background: "#0d0d12" }}><VideoOff className="h-10 w-10" style={{ color: "var(--text-muted)" }} /><p className="text-white font-medium">Video havolasi qo&apos;shilmagan</p><p className="text-sm" style={{ color: "var(--text-muted)" }}>Admin panelda ushbu kinoga video havolasini qo&apos;shing</p></div>}</div></div></div>
    <div className="max-w-[1120px] mx-auto w-full px-4 py-7" style={{ color: "var(--text-primary)" }}><section className="rounded-2xl p-4 md:p-5" style={{ background: "linear-gradient(145deg, rgba(25,18,42,.82), rgba(11,12,21,.94))", border: "1px solid rgba(167,139,250,.2)" }}><div className="flex flex-wrap items-center gap-2 text-xs text-violet-200"><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1" style={{ background: "rgba(124,58,237,.16)" }}><Sparkles className="h-3.5 w-3.5" />Premium tomosha</span>{movie.imdbRating ? <span>IMDb {movie.imdbRating.toFixed(1)}</span> : null}</div><h1 className="mt-3 text-xl md:text-2xl font-bold text-white" style={{ fontFamily: "var(--font-display)" }}>{movie.title}</h1><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[{ icon: CalendarDays, label: "Yil", value: movie.year }, { icon: Globe2, label: "Davlat", value: movie.country }, { icon: Mic2, label: "Dublyaj", value: movie.dubbing }, { icon: Sparkles, label: "Sifat", value: "HD" }].filter((item) => item.value).map(({ icon: Icon, label, value }) => <div key={label} className="rounded-xl px-3 py-2.5" style={{ background: "rgba(255,255,255,.035)", border: "1px solid rgba(255,255,255,.07)" }}><div className="flex items-center gap-1.5 text-xs" style={{ color: "var(--text-muted)" }}><Icon className="h-3.5 w-3.5 text-violet-300" />{label}</div><p className="mt-1 truncate text-sm font-medium text-white">{value}</p></div>)}</div>{movie.description ? <p className="mt-4 max-w-3xl text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>{movie.description}</p> : null}</section></div>
  </div>;
}
