"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Copy, Globe2, MessageCircle, Send, Share2, Star, ThumbsDown, ThumbsUp } from "lucide-react";
import type { Movie } from "@/types/movie";

type Comment = { id: string; body: string; createdAt: string; firstName: string; lastName?: string; telegramUsername?: string; telegramPhotoUrl?: string; role: string; likes: number; likedByMe: boolean };
type Data = { rating: { average: number; count: number; myScore: number }; reaction: { likes: number; dislikes: number; myReaction: "LIKE" | "DISLIKE" | "" }; comments: Comment[]; canComment: boolean };

const card = { background: "linear-gradient(145deg,rgba(18,19,31,.92),rgba(10,11,20,.94))", border: "1px solid var(--border)", boxShadow: "0 12px 32px rgba(0,0,0,.17)" };
const ago = (date: string) => { const min = Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 60_000)); return min < 2 ? "Hozir" : min < 60 ? `${min} daqiqa oldin` : min < 1440 ? `${Math.floor(min / 60)} soat oldin` : new Date(date).toLocaleDateString("uz-UZ"); };

export default function EngagementPanel({ content }: { content: Movie }) {
  const [data, setData] = useState<Data | null>(null);
  const [hover, setHover] = useState(0);
  const [text, setText] = useState("");
  const [replyTo, setReplyTo] = useState<string | undefined>();
  const [sort, setSort] = useState<"latest" | "top">("latest");
  const [toast, setToast] = useState("");
  const [error, setError] = useState("");
  const load = async () => { const r = await fetch(`/api/public/engagement/${content.id}?sort=${sort}`, { cache: "no-store" }); if (r.ok) setData(await r.json()); };
  useEffect(() => { void load(); }, [sort]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2200); };
  const vote = async (body: { score?: number; reaction?: "LIKE" | "DISLIKE" }) => { setError(""); const r = await fetch(`/api/public/engagement/${content.id}/vote`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (!r.ok) setError("Ovoz saqlanmadi. Qayta urinib ko‘ring."); else { notify("Bahoyingiz saqlandi"); void load(); } };
  const share = async (kind: "telegram" | "whatsapp" | "facebook" | "copy") => { const url = window.location.href; const text = `${content.title} — UZDUB Play`; if (kind === "copy") { await navigator.clipboard.writeText(url); return notify("✓ Havola nusxalandi"); } const target = kind === "telegram" ? `https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(text)}` : kind === "whatsapp" ? `https://wa.me/?text=${encodeURIComponent(`${text}\n${url}`)}` : `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`; window.open(target, "_blank", "noopener,noreferrer"); };
  const sendComment = async () => { const r = await fetch(`/api/public/engagement/${content.id}/comments`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text, parentId: replyTo }) }); const json = await r.json(); if (!r.ok) return setError(json.error ?? "Izoh yuborilmadi."); setText(""); setReplyTo(undefined); notify("Izoh yuborildi"); void load(); };
  const likeComment = async (id: string) => { const r = await fetch(`/api/public/engagement/comment-likes/${id}`, { method: "POST" }); if (r.ok) void load(); else setError("Izohni yoqtirish uchun kiring."); };
  const score = hover || data?.rating.myScore || 0;
  const totalReactions = (data?.reaction.likes ?? 0) + (data?.reaction.dislikes ?? 0);
  const typeText = content.type === "SERIAL" ? "Serialni baholang" : "Kinoni baholang";

  return <section className="max-w-[1400px] mx-auto px-4 md:px-8 py-8">
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1.7fr)_minmax(320px,1fr)]">
      <div className="order-3 lg:order-1 rounded-2xl p-4 md:p-5" style={card}>
        <div className="flex items-center justify-between gap-3 mb-4"><h2 className="flex items-center gap-2 text-xl font-bold text-white"><MessageCircle className="h-5 w-5 text-violet-400" />Izohlar <span className="text-sm rounded-full px-2 py-0.5 text-violet-200" style={{ background: "rgba(124,58,237,.17)" }}>{data?.comments.length ?? 0}</span></h2><div className="flex gap-2"><button onClick={() => setSort("latest")} className={`px-3 py-1.5 text-xs rounded-lg ${sort === "latest" ? "text-white" : "text-gray-400"}`} style={sort === "latest" ? { background: "rgba(124,58,237,.3)" } : undefined}>So‘nggi</button><button onClick={() => setSort("top")} className={`px-3 py-1.5 text-xs rounded-lg ${sort === "top" ? "text-white" : "text-gray-400"}`} style={sort === "top" ? { background: "rgba(124,58,237,.3)" } : undefined}>Eng yaxshi</button></div></div>
        {data?.canComment ? <div className="mb-5"><div className="flex gap-2"><textarea value={text} onChange={(e) => setText(e.target.value)} maxLength={800} rows={2} placeholder={replyTo ? "Javobingizni yozing..." : "Izohingizni yozing..."} className="flex-1 rounded-xl p-3 text-sm text-white resize-none outline-none" style={{ background: "rgba(0,0,0,.22)", border: "1px solid var(--border)" }} /><button onClick={sendComment} disabled={text.trim().length < 2} className="self-end px-4 py-3 rounded-xl text-sm font-semibold text-white disabled:opacity-40" style={{ background: "linear-gradient(135deg,#7c3aed,#db2777)" }}><Send className="h-4 w-4" /></button></div>{replyTo && <button onClick={() => setReplyTo(undefined)} className="mt-2 text-xs text-violet-300">Javob berish bekor qilindi</button>}</div> : <div className="mb-5 rounded-xl p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3" style={{ background: "rgba(124,58,237,.08)", border: "1px solid rgba(168,85,247,.26)" }}><div><p className="font-medium text-white">Izoh qoldirmoqchimisiz?</p><p className="text-sm mt-1" style={{ color: "var(--text-muted)" }}>Izoh yozish uchun avval ro‘yxatdan o‘ting.</p></div><Link href="/kirish" className="px-4 py-2.5 rounded-xl text-center text-sm font-semibold text-white" style={{ background: "linear-gradient(135deg,#7c3aed,#db2777)" }}>Kirish / Ro‘yxatdan o‘tish</Link></div>}
        <div className="space-y-3">{data?.comments.map((comment) => <article key={comment.id} className="rounded-xl p-3.5" style={{ background: "rgba(255,255,255,.025)", border: "1px solid rgba(255,255,255,.06)" }}><div className="flex gap-3"><div className="h-9 w-9 rounded-full overflow-hidden flex items-center justify-center text-white font-bold" style={{ background: "linear-gradient(135deg,#7c3aed,#ec4899)" }}>{comment.telegramPhotoUrl ? <img src={comment.telegramPhotoUrl} alt="" className="h-full w-full object-cover" /> : comment.firstName[0]}</div><div className="min-w-0 flex-1"><div className="flex gap-2 items-center"><p className="text-sm font-semibold text-white">{comment.telegramUsername ? `@${comment.telegramUsername}` : `${comment.firstName} ${comment.lastName ?? ""}`}</p>{(comment.role === "ADMIN" || comment.role === "SUPER_ADMIN") && <span className="text-[10px] px-1.5 py-0.5 rounded text-violet-100" style={{ background: "rgba(124,58,237,.36)" }}>ADMIN</span>}<span className="text-xs" style={{ color: "var(--text-muted)" }}>• {ago(comment.createdAt)}</span></div><p className="text-sm leading-relaxed mt-1.5" style={{ color: "var(--text-secondary)" }}>{comment.body}</p><div className="mt-3 flex gap-4"><button onClick={() => likeComment(comment.id)} className={`inline-flex items-center gap-1.5 text-xs ${comment.likedByMe ? "text-yellow-300" : "text-gray-400"}`}><ThumbsUp className={`h-3.5 w-3.5 ${comment.likedByMe ? "fill-current" : ""}`} />{comment.likes}</button>{data.canComment && <button onClick={() => { setReplyTo(comment.id); window.scrollTo({ top: document.documentElement.scrollHeight, behavior: "smooth" }); }} className="text-xs text-violet-300">Javob berish</button>}</div></div></div></article>)}{data && !data.comments.length && <p className="py-8 text-center text-sm" style={{ color: "var(--text-muted)" }}>Birinchi izohni siz qoldiring.</p>}</div>
      </div>
      <aside className="order-1 lg:order-2 space-y-4"><div className="rounded-2xl p-5" style={card}><h2 className="flex gap-2 items-center text-lg font-bold text-white"><Share2 className="h-5 w-5 text-violet-400" />Ulashish</h2><div className="grid grid-cols-4 gap-2 mt-5">{[{ label: "Telegram", icon: Send, action: "telegram" }, { label: "WhatsApp", icon: MessageCircle, action: "whatsapp" }, { label: "Facebook", icon: Globe2, action: "facebook" }, { label: "Nusxalash", icon: Copy, action: "copy" }].map(({ label, icon: Icon, action }) => <button key={label} onClick={() => void share(action as "telegram" | "whatsapp" | "facebook" | "copy")} className="flex flex-col items-center gap-2 text-xs hover:text-violet-200" style={{ color: "var(--text-muted)" }}><span className="h-11 w-11 rounded-full flex items-center justify-center text-white" style={{ background: "rgba(124,58,237,.16)", border: "1px solid rgba(168,85,247,.2)" }}><Icon className="h-5 w-5" /></span>{label}</button>)}</div></div>
      <div className="rounded-2xl p-5" style={card}><h2 className="text-lg font-bold text-white">UzdubPlay uchun reyting</h2><p className="text-sm mt-1" style={{ color: "var(--text-muted)" }}>{typeText}</p><div className="grid grid-cols-10 gap-1 mt-5">{Array.from({ length: 10 }, (_, index) => index + 1).map((value) => <button key={value} onMouseEnter={() => setHover(value)} onMouseLeave={() => setHover(0)} onClick={() => void vote({ score: value })} className="group flex flex-col items-center gap-1 text-xs" style={{ color: score >= value ? "#facc15" : "#94a3b8" }}><Star className={`h-5 w-5 ${score >= value ? "fill-current" : ""}`} />{value}</button>)}</div><p className="mt-4 text-sm text-white">{data?.rating.count ? `${data.rating.average.toFixed(1)} / 10` : "Hali baho yo‘q"} <span className="ml-2" style={{ color: "var(--text-muted)" }}>{data?.rating.count ?? 0} ta baho</span></p><div className="grid grid-cols-2 gap-3 mt-5"><button onClick={() => void vote({ reaction: "LIKE" })} className={`py-2.5 rounded-xl text-sm font-semibold inline-flex justify-center gap-2 ${data?.reaction.myReaction === "LIKE" ? "text-emerald-200" : "text-white"}`} style={{ border: "1px solid rgba(74,222,128,.45)", background: data?.reaction.myReaction === "LIKE" ? "rgba(34,197,94,.14)" : "transparent" }}><ThumbsUp className="h-4 w-4" />Yoqdi</button><button onClick={() => void vote({ reaction: "DISLIKE" })} className={`py-2.5 rounded-xl text-sm font-semibold inline-flex justify-center gap-2 ${data?.reaction.myReaction === "DISLIKE" ? "text-rose-200" : "text-white"}`} style={{ border: "1px solid rgba(251,113,133,.4)", background: data?.reaction.myReaction === "DISLIKE" ? "rgba(244,63,94,.13)" : "transparent" }}><ThumbsDown className="h-4 w-4" />Yoqmadi</button></div><p className="mt-3 text-xs" style={{ color: "var(--text-muted)" }}>👍 {data?.reaction.likes ?? 0} · 👎 {data?.reaction.dislikes ?? 0}{totalReactions ? ` (${Math.round(((data?.reaction.likes ?? 0) / totalReactions) * 100)}% yoqdi)` : ""}</p></div></aside>
    </div>{toast && <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[80] px-4 py-3 rounded-xl text-sm text-white" style={{ background: "rgba(28,20,47,.96)", border: "1px solid rgba(168,85,247,.6)", boxShadow: "0 12px 30px rgba(0,0,0,.35)" }}>{toast}</div>}{error && <p className="mt-3 text-sm text-rose-400">{error}</p>}
  </section>;
}
