"use client";
import { useEffect, useState } from "react";
import { Check, Pencil } from "lucide-react";
import type { StoredUser } from "@/lib/movies-store";

export default function UsersPage() {
  const [users, setUsers] = useState<StoredUser[]>([]); const [editing, setEditing] = useState<string | null>(null);
  useEffect(() => { fetch("/api/admin/users").then((r) => r.json()).then((d) => setUsers(d.users ?? [])); }, []);
  const change = (id: string, patch: Partial<StoredUser>) => setUsers((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item));
  const save = async (user: StoredUser) => { const response = await fetch(`/api/admin/users/${user.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ role: user.role, subscriptionType: user.subscriptionType, isActive: user.isActive }) }); const data = await response.json(); if (!response.ok) return alert(data.error); setUsers((items) => items.map((item) => item.id === user.id ? data.user : item)); setEditing(null); };
  return <div><h1 className="text-2xl font-bold text-white mb-2">Foydalanuvchilar</h1><p className="text-sm mb-6" style={{color:"var(--text-muted)"}}>{users.length} ta haqiqiy Telegram foydalanuvchisi</p><div className="rounded-2xl overflow-x-auto" style={{border:"1px solid var(--border)"}}><table className="w-full min-w-[760px]"><thead><tr>{["Foydalanuvchi","Rol","Obuna","Holat",""].map((title)=><th key={title} className="p-4 text-left text-xs" style={{color:"var(--text-muted)"}}>{title}</th>)}</tr></thead><tbody>{users.map((user)=>{const open=editing===user.id; return <tr key={user.id} style={{borderTop:"1px solid var(--border)"}}><td className="p-4 text-white"><b>{user.firstName} {user.lastName}</b><br/><small style={{color:"var(--text-muted)"}}>{user.telegramUsername ? `@${user.telegramUsername}` : "Username yo'q"}</small></td><td className="p-4">{open ? <select value={user.role} onChange={(e)=>change(user.id,{role:e.target.value})}><option value="USER">Foydalanuvchi</option><option value="ADMIN">Admin</option></select> : <span className="text-white">{user.role}</span>}</td><td className="p-4">{open ? <select value={user.subscriptionType} onChange={(e)=>change(user.id,{subscriptionType:e.target.value as StoredUser["subscriptionType"]})}><option value="FREE">Oddiy</option><option value="PREMIUM">Premium</option></select> : <span className="text-white">{user.subscriptionType}</span>}</td><td className="p-4">{open ? <label className="text-white"><input type="checkbox" checked={user.isActive} onChange={(e)=>change(user.id,{isActive:e.target.checked})}/> Faol</label> : <span style={{color:user.isActive?"#10B981":"#EF4444"}}>{user.isActive?"Faol":"Bloklangan"}</span>}</td><td className="p-4">{open ? <button onClick={()=>save(user)} className="text-emerald-400"><Check/></button> : <button onClick={()=>setEditing(user.id)} className="text-violet-400"><Pencil/></button>}</td></tr>})}</tbody></table></div></div>;
}
