"use client";

import { Suspense, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Filter, Search, X } from "lucide-react";
import type { Movie } from "@/types/movie";
import MovieCard from "@/components/movie/MovieCard";

type Result = { movies: Movie[]; total: number; page: number; pages: number };
const empty: Result = { movies: [], total: 0, page: 1, pages: 1 };
const fields = ["type", "genre", "country", "from", "to", "rating", "language", "dubbing", "sort"] as const;

function QidirishContent() {
  const router = useRouter(); const params = useSearchParams();
  const [query, setQuery] = useState(params.get("q") ?? ""); const [result, setResult] = useState<Result>(empty); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const key = params.toString();
  const setParam = (name: string, value: string) => { const next = new URLSearchParams(params.toString()); value ? next.set(name, value) : next.delete(name); if (name !== "page") next.delete("page"); router.replace(`/qidirish?${next.toString()}`); };
  useEffect(() => { const timer = window.setTimeout(() => { if (query !== (params.get("q") ?? "")) setParam("q", query); }, 400); return () => window.clearTimeout(timer); }, [query]);
  useEffect(() => { setLoading(true); setError(""); fetch(`/api/public/search?${key}`).then(async (r) => r.ok ? r.json() : Promise.reject()).then((data: Result) => setResult(data)).catch(() => { setResult(empty); setError("Qidiruvni yuklab bo‘lmadi."); }).finally(() => setLoading(false)); }, [key]);
  const value = (name: string) => params.get(name) ?? "";
  const clear = () => { setQuery(""); router.replace("/qidirish"); };
  const hasFilters = useMemo(() => fields.some((field) => Boolean(params.get(field))) || Boolean(params.get("q")), [params]);
  const filter = (name: string, label: string, options: [string, string][]) => <label className="block text-xs" style={{ color: "var(--text-muted)" }}>{label}<select value={value(name)} onChange={(e) => setParam(name, e.target.value)} className="mt-1 w-full rounded-xl px-3 py-2.5 text-sm text-white bg-black/20 outline-none" style={{ border: "1px solid var(--border)" }}>{options.map(([v, text]) => <option key={v} value={v}>{text}</option>)}</select></label>;
  return <main className="max-w-[1200px] mx-auto px-4 md:px-8 py-10"><div className="flex items-center justify-between gap-4 mb-6"><div><h1 className="text-3xl font-bold text-white" style={{ fontFamily: "var(--font-display)" }}>Qidiruv</h1><p className="mt-1 text-sm" style={{ color: "var(--text-muted)" }}>Kino va seriallarni aniq filtrlar bilan toping.</p></div>{hasFilters && <button onClick={clear} className="text-sm text-violet-300 inline-flex gap-1"><X className="h-4 w-4" />Tozalash</button>}</div>
    <div className="flex items-center gap-3 px-4 py-3 rounded-2xl" style={{ background: "var(--bg-secondary)", border: "1px solid var(--border-hover)" }}><Search className="h-5 w-5 shrink-0 text-violet-400" /><input autoFocus placeholder="Kino yoki serial nomini kiriting..." value={query} onChange={(e) => setQuery(e.target.value)} className="flex-1 bg-transparent outline-none text-white placeholder-gray-500 text-base" /></div>
    <section className="mt-4 p-4 rounded-2xl" style={{ background: "var(--bg-secondary)", border: "1px solid var(--border)" }}><div className="flex items-center gap-2 mb-3 text-white"><Filter className="h-4 w-4 text-violet-400" /><h2 className="font-semibold">Filtrlar</h2></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{filter("type", "Kontent turi", [["", "Barchasi"], ["MOVIE", "Kino"], ["SERIAL", "Serial"], ["CARTOON", "Multfilm"]])}{filter("sort", "Saralash", [["newest", "Eng yangilar"], ["popular", "Eng mashhurlar"], ["rating", "Reyting bo‘yicha"], ["views", "Eng ko‘p ko‘rilgan"], ["title", "Nomi bo‘yicha"]])}<label className="block text-xs" style={{color:"var(--text-muted)"}}>Janr (slug)<input value={value("genre")} onChange={(e)=>setParam("genre",e.target.value)} placeholder="drama, triller" className="mt-1 w-full rounded-xl px-3 py-2.5 text-sm text-white bg-black/20 outline-none" style={{border:"1px solid var(--border)"}} /></label><label className="block text-xs" style={{color:"var(--text-muted)"}}>Mamlakat<input value={value("country")} onChange={(e)=>setParam("country",e.target.value)} placeholder="Janubiy Koreya" className="mt-1 w-full rounded-xl px-3 py-2.5 text-sm text-white bg-black/20 outline-none" style={{border:"1px solid var(--border)"}} /></label><label className="block text-xs" style={{color:"var(--text-muted)"}}>Boshlanish yili<input type="number" value={value("from")} onChange={(e)=>setParam("from",e.target.value)} className="mt-1 w-full rounded-xl px-3 py-2.5 text-sm text-white bg-black/20 outline-none" style={{border:"1px solid var(--border)"}} /></label><label className="block text-xs" style={{color:"var(--text-muted)"}}>Tugash yili<input type="number" value={value("to")} onChange={(e)=>setParam("to",e.target.value)} className="mt-1 w-full rounded-xl px-3 py-2.5 text-sm text-white bg-black/20 outline-none" style={{border:"1px solid var(--border)"}} /></label><label className="block text-xs" style={{color:"var(--text-muted)"}}>Minimal IMDb<input type="number" min="0" max="10" step="0.1" value={value("rating")} onChange={(e)=>setParam("rating",e.target.value)} className="mt-1 w-full rounded-xl px-3 py-2.5 text-sm text-white bg-black/20 outline-none" style={{border:"1px solid var(--border)"}} /></label><label className="block text-xs" style={{color:"var(--text-muted)"}}>Til / Dublyaj<input value={value("language")} onChange={(e)=>setParam("language",e.target.value)} placeholder="Koreys" className="mt-1 w-full rounded-xl px-3 py-2.5 text-sm text-white bg-black/20 outline-none" style={{border:"1px solid var(--border)"}} /></label></div></section>
    <div className="mt-7">{loading ? <p style={{color:"var(--text-muted)"}}>Natijalar yuklanmoqda...</p> : error ? <p className="text-rose-300">{error}</p> : <><p className="text-sm mb-4" style={{color:"var(--text-muted)"}}>{result.total} ta natija</p>{result.movies.length ? <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">{result.movies.map((movie)=><MovieCard key={movie.id} movie={movie} />)}</div> : <div className="text-center py-16 rounded-2xl" style={{background:"var(--bg-secondary)",border:"1px solid var(--border)"}}><Search className="h-12 w-12 mx-auto mb-4 text-violet-400" /><p className="text-lg font-medium text-white">Kino topilmadi</p><p className="mt-2" style={{color:"var(--text-muted)"}}>Filtrlarni o‘zgartirib qayta urinib ko‘ring.</p></div>}{result.pages > 1 && <div className="flex justify-center gap-3 mt-8"><button disabled={result.page===1} onClick={()=>setParam("page",String(result.page-1))} className="px-4 py-2 rounded-xl text-white disabled:opacity-40" style={{border:"1px solid var(--border)"}}>Oldingi</button><span className="px-4 py-2 text-sm" style={{color:"var(--text-muted)"}}>{result.page} / {result.pages}</span><button disabled={result.page===result.pages} onClick={()=>setParam("page",String(result.page+1))} className="px-4 py-2 rounded-xl text-white disabled:opacity-40" style={{border:"1px solid var(--border)"}}>Keyingi</button></div>}</>}</div></main>;
}

export default function QidirishPage() {
  return <Suspense fallback={<main className="max-w-[1200px] mx-auto px-4 md:px-8 py-10"><div className="h-10 w-52 rounded-xl bg-white/5 animate-pulse" /><div className="mt-6 h-14 rounded-2xl bg-white/5 animate-pulse" /><div className="mt-4 h-56 rounded-2xl bg-white/5 animate-pulse" /></main>}><QidirishContent /></Suspense>;
}
