"use client";

import { useEffect, useState } from "react";
import { signIn } from "next-auth/react";
import Link from "next/link";
import { CheckCircle2, Clock3, ExternalLink, Loader2, Play, Send, XCircle } from "lucide-react";

type Flow = "IDLE" | "CREATING" | "WAITING" | "VERIFIED" | "EXPIRED" | "ERROR";
type AuthRequest = { id: string; expiresAt: string; deepLink: string };

export default function TelegramLoginCard() {
  const [flow, setFlow] = useState<Flow>("IDLE"); const [request, setRequest] = useState<AuthRequest | null>(null); const [seconds, setSeconds] = useState(600); const [error, setError] = useState("");
  const start = async () => { setFlow("CREATING"); setError(""); try { const response = await fetch("/api/auth/telegram/create", { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Havola yaratilmagan"); setRequest(data); setSeconds(Math.max(0, Math.floor((new Date(data.expiresAt).getTime() - Date.now()) / 1000))); setFlow("WAITING"); window.open(data.deepLink, "_blank", "noopener,noreferrer"); } catch (e) { setError(e instanceof Error ? e.message : "Xatolik yuz berdi"); setFlow("ERROR"); } };
  const complete = async () => { setFlow("VERIFIED"); const response = await fetch("/api/auth/telegram/complete", { method: "POST" }); const data = await response.json(); if (!response.ok) { setError(data.error || "Kirish yakunlanmadi"); setFlow("ERROR"); return; } const login = () => signIn("telegram", { code: data.code, redirect: false, redirectTo: "/" }); let result = await login(); if (result?.error) result = await login(); if (result?.error) { setError("Kirish yakunlanmadi. Yangi havola yarating."); setFlow("ERROR"); return; } window.location.href = "/"; };
  useEffect(() => { if (flow !== "WAITING" || !request) return; const tick = window.setInterval(() => setSeconds(Math.max(0, Math.floor((new Date(request.expiresAt).getTime() - Date.now()) / 1000))), 1000); const poll = window.setInterval(async () => { const response = await fetch(`/api/auth/telegram/status/${request.id}`, { cache: "no-store" }); const data = await response.json(); if (data.status === "VERIFIED") { window.clearInterval(poll); window.clearInterval(tick); void complete(); } if (data.status === "EXPIRED") { window.clearInterval(poll); window.clearInterval(tick); setFlow("EXPIRED"); } }, 2000); return () => { window.clearInterval(tick); window.clearInterval(poll); }; }, [flow, request]);
  const time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  return <div className="w-full max-w-md p-7 sm:p-8 rounded-3xl relative overflow-hidden" style={{ background: "linear-gradient(145deg, rgba(22,20,35,0.98), rgba(13,12,22,0.98))", border: "1px solid rgba(167,139,250,0.35)", boxShadow: "0 20px 70px rgba(0,0,0,0.38), 0 0 42px rgba(124,58,237,0.14)" }}><div className="absolute -top-24 -right-20 h-48 w-48 rounded-full blur-3xl" style={{ background: "rgba(124,58,237,0.3)" }} />
    <div className="relative"><div className="flex items-center justify-center gap-2 mb-7"><div className="h-10 w-10 rounded-xl flex items-center justify-center" style={{ background: "linear-gradient(135deg, #7C3AED, #EC4899)" }}><Play className="h-5 w-5 text-white fill-white" /></div><span className="text-2xl font-bold"><span className="gradient-text">UZDUB</span><span className="text-white"> Play</span></span></div>
    <h1 className="text-2xl font-bold text-white text-center mb-2">UZDUB Play&apos;ga kirish</h1><p className="text-center mb-7 text-sm" style={{ color: "var(--text-muted)" }}>Telegram orqali xavfsiz ro&apos;yxatdan o&apos;ting yoki akkauntingizga kiring.</p>
    {(flow === "IDLE" || flow === "ERROR" || flow === "EXPIRED") && <><button onClick={start} className="w-full flex items-center justify-center gap-3 py-3.5 rounded-xl font-semibold text-white transition-all hover:scale-[1.02]" style={{ background: "linear-gradient(135deg, #2AABEE, #229ED9)", boxShadow: "0 8px 24px rgba(42,171,238,0.24)" }}><Send className="h-5 w-5 fill-white" />{flow === "EXPIRED" ? "Yangi havola yaratish" : "Telegram orqali davom etish"}</button>{error && <p className="mt-4 text-center text-sm text-red-400">{error}</p>}{flow === "EXPIRED" && <p className="mt-4 text-center text-sm text-amber-300">Havola muddati tugadi. Xavfsizlik sababli yangi havola yarating.</p>}</>}
    {flow === "CREATING" && <State icon={<Loader2 className="animate-spin text-violet-400" />} text="Xavfsiz havola yaratilmoqda..." />}
    {flow === "WAITING" && request && <div className="text-center"><State icon={<Loader2 className="animate-spin text-sky-400" />} text="Telegram orqali tasdiqlash kutilmoqda..." /><div className="mt-4 flex items-center justify-center gap-2 text-sm" style={{ color: "var(--text-muted)" }}><Clock3 className="h-4 w-4" />Havola {time} amal qiladi</div><a href={request.deepLink} target="_blank" rel="noreferrer" className="mt-5 w-full flex items-center justify-center gap-2 py-3 rounded-xl text-sm font-semibold" style={{ border: "1px solid rgba(42,171,238,0.5)", color: "#65c9f8" }}><ExternalLink className="h-4 w-4" />Telegramni ochish</a><button onClick={() => { setRequest(null); setFlow("IDLE"); }} className="mt-3 text-sm" style={{ color: "var(--text-muted)" }}>Bekor qilish</button></div>}
    {flow === "VERIFIED" && <State icon={<CheckCircle2 className="text-emerald-400" />} text="Telegram tasdiqlandi. Akkauntingizga kirmoqdamiz..." />}
    <p className="text-center text-xs mt-6" style={{ color: "var(--text-muted)" }}>Davom etib, siz <Link href="/shartlar" style={{ color: "var(--accent-violet)" }}>foydalanish shartlari</Link>ga rozilik bildirasiz.</p></div></div>;
}
function State({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="py-5 flex flex-col items-center gap-3 text-center"><div className="h-12 w-12 rounded-2xl flex items-center justify-center" style={{ background: "rgba(124,58,237,0.12)" }}>{icon}</div><p className="text-sm text-white">{text}</p></div>; }
